<?php

declare(strict_types=1);

namespace AaiEduHr\HeartPhrameModuleTask\Service;

use DOMDocument;
use DOMElement;
use DOMXPath;

use function libxml_clear_errors;
use function libxml_use_internal_errors;
use function preg_match;
use function trim;

/**
 * HR: Čita deklarativne task-list widgete iz HTML-a. Definicija zadatka ostaje
 *     dio verzije dokumenta, dok se promjenjivo stanje sprema odvojeno.
 * EN: Reads declarative task-list widgets from HTML. The task definition
 *     remains part of the document version while mutable state is stored separately.
 */
final class TaskDefinitionParser
{
    /**
     * HR: Vraća sve valjane zadatke iz dokumenta bez izvođenja HTML sadržaja.
     * EN: Returns all valid tasks from a document without executing HTML content.
     *
     * @return list<TaskDefinition>
     */
    public function parse(string $html): array
    {
        [$document, $root] = $this->document($html);
        if (!$root instanceof DOMElement) {
            return [];
        }

        $xpath = new DOMXPath($document);
        $lists = $xpath->query('.//*[@data-editor-html-task-list="1"]', $root);
        if ($lists === false) {
            return [];
        }

        $definitions = [];
        foreach ($lists as $list) {
            if (!$list instanceof DOMElement) {
                continue;
            }

            $listUuid = trim($list->getAttribute('data-task-list-uuid'));
            if (!$this->isUuid($listUuid)) {
                continue;
            }

            /*
             * HR: Naslov je zajednički naziv liste za prikaz i praćenje. Ne
             *     izvodi se iz teksta prvog retka jer se retci mogu mijenjati.
             * EN: The heading is the shared list label for display and following.
             *     It is not derived from the first row because rows may change.
             */
            $listLabel = $this->listLabel($xpath, $list);
            $scope = $list->getAttribute('data-task-toggle-scope') === 'viewers'
            ? 'viewers'
            : 'editors';
            $items = $xpath->query('.//*[@data-task-uuid]', $list);
            if ($items === false) {
                continue;
            }

            foreach ($items as $item) {
                if (!$item instanceof DOMElement) {
                    continue;
                }

                $taskUuid = trim($item->getAttribute('data-task-uuid'));
                $text = trim($item->textContent);
                if (!$this->isUuid($taskUuid)) {
                    continue;
                }

                if ($text === '') {
                    continue;
                }

                $definitions[] = new TaskDefinition(
                    $taskUuid,
                    $listUuid,
                    $text,
                    $scope,
                    $listLabel,
                );
            }
        }

        return $definitions;
    }

    /**
     * HR: Čita prvi naslov liste bez pretpostavke o njegovoj HTML razini.
     * EN: Reads the list's first heading without assuming its HTML level.
     */
    private function listLabel(DOMXPath $xpath, DOMElement $list): string
    {
        $headings = $xpath->query('.//*[self::h2 or self::h3 or self::h4][1]', $list);
        if ($headings === false) {
            return '';
        }

        $heading = $headings->item(0);

        return $heading instanceof DOMElement ? trim($heading->textContent) : '';
    }

    /**
     * HR: Traži jedan zadatak po stabilnom UUID-u.
     * EN: Finds one task by its stable UUID.
     */
    public function find(string $html, string $taskUuid): ?TaskDefinition
    {
        foreach ($this->parse($html) as $definition) {
            if ($definition->uuid === $taskUuid) {
                return $definition;
            }
        }

        return null;
    }

    /**
     * HR: Parsira fragment unutar sigurnog korijenskog elementa.
     * EN: Parses a fragment inside a safe root element.
     *
     * @return array{DOMDocument, DOMElement|null}
     */
    private function document(string $html): array
    {
        $document = new DOMDocument('1.0', 'UTF-8');
        $previous = libxml_use_internal_errors(true);
        $document->loadHTML(
            '<?xml encoding="UTF-8"><!doctype html><html><body>'
            . '<div id="task-module-root">' . $html . '</div></body></html>',
            LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD,
        );
        libxml_clear_errors();
        libxml_use_internal_errors($previous);

        $root = $document->getElementById('task-module-root');

        return [$document, $root instanceof DOMElement ? $root : null];
    }

    /**
     * HR: Prihvaća samo standardni UUID zapis koji generira editor.
     * EN: Accepts only the standard UUID representation generated by the editor.
     */
    private function isUuid(string $value): bool
    {
        return preg_match(
            '/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',
            $value,
        ) === 1;
    }
}
